[server]
headless = false
address = "localhost"
port = 8501

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#424242"
font = "sans serif"
